site_name: Libreconha
repo_url: https://github.com/tediousrock/libreconha/
nav:
  - Inicio: index.md
  - Cultivo:
    - Equipamentos: equipamentos.md
    - Luz: luz.md
    - Umidade: umidade.md
    - Temperatura: temperatura.md
    - Solo vivo: solovivo.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
  palette:
    - scheme: default
      primary: green
      accent: green
  favicon: assets/favicon.ico
  logo: assets/logo.png
