site_name: Libreconha
repo_url: https://github.com/tediousrock/libreconha/
plugins:
  - glightbox
markdown_extensions:
  - attr_list
  - md_in_html
nav:
  - Inicio: index.md
  - Estufa Básica: estufabasica.md
  - Legalize: legalize.md
  - Cultivo:
    - Equipamentos: equipamentos.md
    - Ventilação: ventilacao.md
    - Sementes: sementes.md
    - Luz: luz.md
    - Umidade: umidade.md
    - Temperatura: temperatura.md
    - Substrato: substrato.md
    - Solo vivo: solovivo.md

theme:
  name: material
  language: pt-BR
  features:
    - navigation.instant
    - navigation.sections
  palette:
    - scheme: default
      primary: green
      accent: green
  favicon: assets/favicon.ico
  logo: assets/logo.png


