site_name: Libreconha
repo_url: https://github.com/tediousrock/libreconha/
plugins:
  - glightbox
  - search:
      lang: pt
markdown_extensions:
  - attr_list
  - md_in_html
nav:
  - Inicio: index.md
  - Legalize: legalize.md
  - Cultivo:
    - Estufa Básica: estufabasica.md
    - Equipamentos: equipamentos.md
    - Ventilação: ventilacao.md
    - Sementes: sementes.md
    - Luz: luz.md
    - Umidade: umidade.md
    - Temperatura: temperatura.md
    - Substrato: substrato.md
    - Solo vivo: solovivo.md
    - Dedetização: dedetizacao.md

copyright: Copyright &copy; 2023 tediousrock

extra:
  generator: false
  social:
    - icon: fontawesome/brands/reddit 
      link: https://www.reddit.com/r/libreconha/
      name: libreconha subreddit
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/u/tediousrock/
      name: tediousrock reddit

theme:
  font:
    text: Roboto
  name: material
  language: pt-BR
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
  palette: 
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  favicon: assets/favicon.ico
  logo: assets/logo.png


