site_name: Libreconha
nav:
    - Inicio: index.md
    - Equipamentos: equipamentos.md
    - Luz: luz.md
    - Umidade: umidade.md
    - Temperatura: temperatura.md
    - Solo vivo: solovivo.md

theme:
  name: material
  palette:
    - scheme: default
      primary: green
      accent: green
  favicon: assets/favicon.ico
  logo: assets/logo.png
